"""New Migration

Revision ID: 444524876911
Revises: 
Create Date: 2023-05-08 17:11:45.913804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '444524876911'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plante',
    sa.Column('id_plante', sa.Integer(), nullable=False),
    sa.Column('nom_plante', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_plante')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=True),
    sa.Column('prenom', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('mot_de_passe', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('conseil',
    sa.Column('id_conseil', sa.Integer(), nullable=False),
    sa.Column('id_botaniste', sa.Integer(), nullable=True),
    sa.Column('id_plante', sa.Integer(), nullable=True),
    sa.Column('date_conseil', sa.Date(), nullable=True),
    sa.Column('texte_conseil', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_botaniste'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['id_plante'], ['plante.id_plante'], ),
    sa.PrimaryKeyConstraint('id_conseil')
    )
    op.create_table('contact',
    sa.Column('id_contact', sa.Integer(), nullable=False),
    sa.Column('id_user1', sa.Integer(), nullable=True),
    sa.Column('id_user2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user1'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['id_user2'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_contact')
    )
    op.create_table('garde',
    sa.Column('id_garde', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_plante', sa.Integer(), nullable=True),
    sa.Column('date_garde', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_plante'], ['plante.id_plante'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_garde')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('garde')
    op.drop_table('contact')
    op.drop_table('conseil')
    op.drop_table('user')
    op.drop_table('plante')
    # ### end Alembic commands ###
